//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Suelo"",
            ""id"": ""879c3653-e12b-4575-b6bd-7f6ba5bfe113"",
            ""actions"": [
                {
                    ""name"": ""WASD"",
                    ""type"": ""Value"",
                    ""id"": ""24e4d50c-47db-4499-8a44-3194432a7da9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseInput"",
                    ""type"": ""Value"",
                    ""id"": ""5eacfe54-23e8-4c16-9d7e-a3ceffb6b5f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b8dd1205-207c-4e46-926b-2b86d7ef3a54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""5b412cb4-946c-41aa-9f2d-a98f14720e8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""fa615959-67c1-4a71-a588-dcdc73a3d622"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""46b6a5d4-fa30-42ad-9d9d-9e420043fa26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BoogieCam"",
                    ""type"": ""Button"",
                    ""id"": ""b9e5f825-1f60-462c-bec7-a2b910a7ea91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""23046d6f-8c9d-49ba-a601-f30234c27a68"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""150d2c54-031e-4282-a506-28071dd1fe91"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": ""Normalize"",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e4b3d4df-7f53-4d94-8a88-f85004c567f5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""17668c82-7820-492e-9501-20e9e3567c3d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fde5c573-827d-4b77-b8db-930cac46da85"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9308aa0b-4924-4f33-a57e-5f356036f54b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8944255c-e37c-444c-a2ee-f0484b907def"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""111c01fe-efcc-477c-b7f1-034fab13d489"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0d7902d-39cd-47fc-8d36-9c7837e70cf7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bd04a34-b0f9-40d6-82f2-c7e49e1ae152"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""768331f6-592f-471a-bceb-d4bcf50e15d8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""946c93e5-a75b-4298-a9c9-53d344135325"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f63b9cf-8f27-4a17-b6c3-40b0a825ffff"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27e6dfb9-6769-4fab-8ce9-493910131b52"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BoogieCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Suelo
        m_Suelo = asset.FindActionMap("Suelo", throwIfNotFound: true);
        m_Suelo_WASD = m_Suelo.FindAction("WASD", throwIfNotFound: true);
        m_Suelo_MouseInput = m_Suelo.FindAction("MouseInput", throwIfNotFound: true);
        m_Suelo_Jump = m_Suelo.FindAction("Jump", throwIfNotFound: true);
        m_Suelo_Shoot = m_Suelo.FindAction("Shoot", throwIfNotFound: true);
        m_Suelo_ChangeWeapon = m_Suelo.FindAction("ChangeWeapon", throwIfNotFound: true);
        m_Suelo_Reload = m_Suelo.FindAction("Reload", throwIfNotFound: true);
        m_Suelo_BoogieCam = m_Suelo.FindAction("BoogieCam", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Suelo
    private readonly InputActionMap m_Suelo;
    private ISueloActions m_SueloActionsCallbackInterface;
    private readonly InputAction m_Suelo_WASD;
    private readonly InputAction m_Suelo_MouseInput;
    private readonly InputAction m_Suelo_Jump;
    private readonly InputAction m_Suelo_Shoot;
    private readonly InputAction m_Suelo_ChangeWeapon;
    private readonly InputAction m_Suelo_Reload;
    private readonly InputAction m_Suelo_BoogieCam;
    public struct SueloActions
    {
        private @PlayerInput m_Wrapper;
        public SueloActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @WASD => m_Wrapper.m_Suelo_WASD;
        public InputAction @MouseInput => m_Wrapper.m_Suelo_MouseInput;
        public InputAction @Jump => m_Wrapper.m_Suelo_Jump;
        public InputAction @Shoot => m_Wrapper.m_Suelo_Shoot;
        public InputAction @ChangeWeapon => m_Wrapper.m_Suelo_ChangeWeapon;
        public InputAction @Reload => m_Wrapper.m_Suelo_Reload;
        public InputAction @BoogieCam => m_Wrapper.m_Suelo_BoogieCam;
        public InputActionMap Get() { return m_Wrapper.m_Suelo; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SueloActions set) { return set.Get(); }
        public void SetCallbacks(ISueloActions instance)
        {
            if (m_Wrapper.m_SueloActionsCallbackInterface != null)
            {
                @WASD.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnWASD;
                @WASD.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnWASD;
                @WASD.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnWASD;
                @MouseInput.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnMouseInput;
                @MouseInput.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnMouseInput;
                @MouseInput.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnMouseInput;
                @Jump.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnJump;
                @Shoot.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnShoot;
                @ChangeWeapon.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnChangeWeapon;
                @Reload.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnReload;
                @BoogieCam.started -= m_Wrapper.m_SueloActionsCallbackInterface.OnBoogieCam;
                @BoogieCam.performed -= m_Wrapper.m_SueloActionsCallbackInterface.OnBoogieCam;
                @BoogieCam.canceled -= m_Wrapper.m_SueloActionsCallbackInterface.OnBoogieCam;
            }
            m_Wrapper.m_SueloActionsCallbackInterface = instance;
            if (instance != null)
            {
                @WASD.started += instance.OnWASD;
                @WASD.performed += instance.OnWASD;
                @WASD.canceled += instance.OnWASD;
                @MouseInput.started += instance.OnMouseInput;
                @MouseInput.performed += instance.OnMouseInput;
                @MouseInput.canceled += instance.OnMouseInput;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @BoogieCam.started += instance.OnBoogieCam;
                @BoogieCam.performed += instance.OnBoogieCam;
                @BoogieCam.canceled += instance.OnBoogieCam;
            }
        }
    }
    public SueloActions @Suelo => new SueloActions(this);
    public interface ISueloActions
    {
        void OnWASD(InputAction.CallbackContext context);
        void OnMouseInput(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnBoogieCam(InputAction.CallbackContext context);
    }
}
